### ISSUE TITLE
GeologicalContext field in template is a Darwin Core Class level term

### ISSUE THREAD

**Issue by jdeck88** [futres/template#12]
GeologicalContext is put in the template but this is, i think, i class level term and we are not using these in the template....  I believe it should be removed....

**Comment by lbrensk** [comment]
Agreed, it is a class level term. There are specific terms for expressing geological context https://dwc.tdwg.org/terms/#geologicalcontext

What data in our examples (Ray, Kitty, or VertNet data) are we trying to convey with this? That may help us better determine what field(s) we need.

**Comment by megbalk** [comment]
I think I got confused, sorry. I thought we were saying it should be used for the name of the quarry? Quarry is currently in sitename.

**Comment by jdeck88** [comment]
this issue can be closed now, reference #8

**Comment by jdeck88** [comment]
geologicalContext is in current release of template v1.0.5  re-opening issue so it can be removed from template.

**Comment by megbalk** [comment]
You're right - I will remove it.
