### ISSUE TITLE
samplingProtocol

### ISSUE THREAD

**Issue by megbalk** [futres/template#21]

**Comment by jdeck88** [comment]
is this issue the same as #32 ?
also, i have this term in the GEOME template. 
On call yesterday we were discussing going with the DwC definition/usage which says that you can 
provide a written description of protocol or a URI.  we can provide special direction to folks to use Protocols.io

**Comment by megbalk** [comment]
I think you're right that it's the same. I got confused - this was pre-call yesterday.
