### ISSUE TITLE
Protocol for addressing term changes/additions

### ISSUE THREAD

**Issue by jdeck88** [futres/template#34]
I propose using GEOME as the location for template term additions.  We can use the following URL to link to the FUTRES team terminology:

https://geome-db.org/workbench/template?projectId=156

So, when we propose terms for discussion, e.g. #16 or #8, we can provide a discussion on the issue tracker, and then when we have some agreement, i can make the changes to GEOME.  Since some of the terms we are proposing are new, and need to be added to the GEOME network, i suggest i handle this part.  

This means, we should direct users to generate template worksheets from the GEOME website (see above URL) instead of the template.csv file in this repository.  I need feedback from the group if you want to go this route...

**Comment by megbalk** [comment]
Great idea. I'll delete the pre-made templates as those are now obsolete.

**Comment by jdeck88** [comment]
proposal is to keep using the templates CSV file and making releases in the futres template repository periodically and then any release will be applied to GEOME by John after the release.
