### ISSUE TITLE
ageValue and ageUnit

### ISSUE THREAD

**Issue by jdeck88** [futres/template#38]
We need definitions for these terms.

**Comment by megbalk** [comment]
ageValue: numerical value indicating how old in hours, days, weeks, months, or years the individual is.
ageUnit: unit for the ageValue in hours, days, weeks, months, or years

**Comment by jdeck88** [comment]
I added ageEstimationMethod to this issue... @megbalk can you come up with a definition for that one as well?

Also, i recommend the following Controlled Vocab for ageUnit (hour, day, week, month, year). In other areas of GEOME we use mainly two character abbreviations for units (e.g. kg, km, ft, lb, oz) but i think in this case writing out the required units in full is better.

**Comment by megbalk** [comment]
ageValue: numerical value indicating how old in hours, days, weeks, months, or years the individual is a time of death (paleo and zooarchaeological), collection (neoecological), or observation (non-specimen observations).

ageEstimationMethod: free text field for description of method for determining ageValue.

**Comment by megbalk** [comment]
adding verbatimAgeValue for those ages that are ranges (e.g., ~2-3 yrs).
