### ISSUE TITLE
collectionOfOrganismsID

### ISSUE THREAD

**Issue by jdeck88** [futres/template#39]
We need a better definition for this. currently the under "example" in the template, it says:

"identifier for the collection of Organisms referred to".  

This concept is not in Darwin Core (or, maybe it is, but under a different name) and i really need to understand better what we're talking about before adding it in GEOME.  Can we expand on the use case here in the github issues section?

**Comment by megbalk** [comment]
It refers to if it is a single bone, an entire individual, or a lot.

**Comment by megbalk** [comment]
get rid of term, encompassed by organismID
