### ISSUE TITLE
References

### ISSUE THREAD

**Issue by megbalk** [futres/template#4]
These are for the methodology of the measurement.

**Comment by jdeck88** [comment]
We already have  measurementMethod (http://rs.tdwg.org/dwc/terms/measurementMethod) defined in the template (and a required term).  See https://geome-db.org/workbench/template?projectId=156 

This should address the issue so closing this, but clarify if i'm missing something here @megbalk

**Comment by megbalk** [comment]
I think it was for the reference for the measurement method (somewhere in-between protocol and a standard guide). Currently we have these as annotations in the ontology.

**Comment by jdeck88** [comment]
Unsure of status here... do we still need this open?
