### ISSUE TITLE
Revisit suggested and required fields

### ISSUE THREAD

**Issue by jdeck88** [futres/template#45]
Based on template v1.0.6 there are 57 (out of 58) that are either suggested or required.  In my experience, if we put this many entailments on incoming data it will make it difficult for people to contribute data. 

First item:
"suggested" fields will throw a warning when data loading if not present.  With nearly every field as suggested it defeats the purpose of this.  We should only make fields "suggested" if it is indeed really important to include, that is, important enough to annoy the user with a warning when loading data.  

Second item:
I'm not sure these two fields should be required: verbatimEventDate, references
Three more which we can discuss are: institutionCode, collectionCode, and catalogNumber.  Are there data sources which may not have these items?    For a reference, neither Kitty's or Ray's sample data sets had any of these fields initially offered.  Was there a reason for that, or was it just an oversight?

The others listed as required in the template seem reasonable.

**Comment by megbalk** [comment]
Can the field be blank? I added in suggested if it wasn't required.

**Comment by jdeck88** [comment]
There are alot fewer suggested and required fields... closing this issue.
