### ISSUE TITLE
fieldNotes or eventRemarks

### ISSUE THREAD

**Issue by megbalk** [futres/template#46]
seem to be similar based on DwC.

**Comment by megbalk** [comment]
fieldNotes: can have a URI...points to notebook?
note about why collected things together
eventRemarks: about the event itself

**Comment by megbalk** [comment]
keep eventRemarks, ignore fieldNotes as it does not seem to have a good definition.

**Comment by megbalk** [comment]
kitty would like this added as it can potentially give exact locations for field beds

**Comment by jdeck88** [comment]
I think we should be able to put this information in eventRemarks... I agree the DwC definition for fieldNotes is not very good.

**Comment by megbalk** [comment]
agreed. Will leave out.
