### ISSUE TITLE
informationWithheld

### ISSUE THREAD

**Issue by megbalk** [futres/template#56]
suggested by Kitty; http://rs.tdwg.org/dwc/iri/informationWithheld

**Comment by megbalk** [comment]
perhaps there's a way to do this in GEOME?

**Comment by jdeck88** [comment]
We should add the regular dwc term to the template:

http://rs.tdwg.org/dwc/terms/informationWithheld

not the term from the IRI namespace as i highly doubt anyone has assigned IRIs for their informationWithheld remarks.

**Comment by megbalk** [comment]
Will do. But, I don't think it means "do not share", I think it's a place to write information not shared in the dataset.

**Comment by megbalk** [comment]
informationWithheld just gives information about how information was potentially obscured.

**Comment by megbalk** [comment]
added informationWithheld
