### ISSUE TITLE
skeletalElementURI

### ISSUE THREAD

**Issue by megbalk** [futres/template#59]
suggested by Kitty

**Comment by megbalk** [comment]
my understanding is that we're not having URI...but I forget why

**Comment by jdeck88** [comment]
We have skeletalElement issue in #48 ... i think we were going to be minting a new term for this and also, i don't think it will be common to have URIs for skeletalElements.  If someone does have a URI for a skeletalElement they can put it in the skeletalElement term itself.

**Comment by megbalk** [comment]
Agreed, I'll leave it out for now
