### ISSUE TITLE
synonymous terms

### ISSUE THREAD

**Issue by megbalk** [futres/template#61]
1. What is the difference between materialSampleID and organismID?
2. What is the difference between measurementMethod and samplingProtocol?

**Comment by jdeck88** [comment]
A materialSampleID is an identifier for the physical results of a sampling event.  It is more broad than organism and hence suitable to represent any type of thing: e.g. environmental sample which may or may not be an organism.  An organism can be an individual or multiple individuals (e.g a wolf pack).  An individual is a single individual.  

samplingProtocol describes the method by which a sample was removed from the natural environment or the manner in which a sub-sample was extracted.  the measurementMethod is the manner in which something is measured...

**Comment by megbalk** [comment]
Thanks!
