### ISSUE TITLE
Rethink suggestion verbatimLatitude, verbatimLong, and verbatimLocality

### ISSUE THREAD

**Issue by jdeck88** [futres/template#66]
I don't think we need to suggest these fields for users since we already have locality required and decimalLatitude and decimalLongitude required.  Typically, users already have their data filled for locality, decimalLat, and decimalLong and ignore the verbatim fields.  The verbatim forms of lat/lng usually only come into play when these values were collected in UTM or Stateplane coordinates or DMS, which is pretty rare.  As for verbatimLocality, this is the "original textual description of a place"... The vast majority of cases this is the same as locality.

**Comment by megbalk** [comment]
changed.
