### ISSUE TITLE
reproductive condition

### ISSUE THREAD

**Issue by megbalk** [futres/template#69]
All for Adults:
Reproductive = pregnant (female), lactating (female), enlarged nipples (female), scrotal (male)
Non-Reproductive = not pregnant (female), not lactating (female), non-scrotal (male)

**Comment by jdeck88** [comment]
So, for reproductiveCondition we have currently:
```
non-reproductive
pregnant
```

Not sure what the proposal is here.  In any case, i think best to keep the original terms and add in the new ones?  And any reason to append the sex after each term?  seems redundant.  Proposal:
```
non-reproductive
pregnant
lactating
enlarged nipples
scrotal
not pregnant
not lactating
non-scrotal
```

**Comment by megbalk** [comment]
I'll add these to data mapping.
