### ISSUE TITLE
chronometric age reference system

### ISSUE THREAD

**Issue by megbalk** [futres/template#71]
can we add a controlled vocabulary or examples under DEF in GEOME?
https://docs.google.com/spreadsheets/d/1hXIXU6dPg4FioheBhJW6tayxcxepLS-2KgOLikMjJmw/edit#gid=555326812

**Comment by jdeck88** [comment]
This is the list.. make this a CV:
"kya","mya","BP","AD","BCE"

**Comment by megbalk** [comment]
Perhaps also add: ACE, BC

**Comment by jdeck88** [comment]
fixed.
